# Generated by Django 3.2.5 on 2021-07-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_detail_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=50)),
                ('password', models.CharField(default='password', max_length=50)),
                ('useragent', models.CharField(default='useragent', max_length=50)),
                ('proxy', models.CharField(default='proxy', max_length=50)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
