# Generated by Django 3.2.5 on 2021-07-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_auto_20210727_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='proxy',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='useragent',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
