# Generated by Django 3.2.5 on 2021-07-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_auto_20210727_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='useragent',
        ),
    ]
