# Generated by Django 3.2.5 on 2021-08-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0008_auto_20210731_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Needs_8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_1c_part', models.CharField(default='', max_length=36)),
                ('id_1c_doc', models.CharField(default='', max_length=36)),
                ('part_sought', models.CharField(default='', max_length=64)),
                ('brand_sought', models.CharField(default='', max_length=128)),
                ('status', models.IntegerField()),
            ],
            options={
                'verbose_name': 'needs_8',
            },
        ),
    ]
