# Generated by Django 3.2.5 on 2021-08-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0009_needs_8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needs_8',
            name='brand_sought',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='needs_8',
            name='id_1c_doc',
            field=models.CharField(default='', max_length=38),
        ),
        migrations.AlterField(
            model_name='needs_8',
            name='id_1c_part',
            field=models.CharField(default='', max_length=38),
        ),
        migrations.AlterField(
            model_name='needs_8',
            name='part_sought',
            field=models.CharField(default='', max_length=255),
        ),
    ]
